AUDIO_ENABLE = no           # Audio output
BACKLIGHT_ENABLE = no       # Keyboard backlight functionality
BOOTMAGIC_ENABLE = yes      # Bootmagic Lite
BLUETOOTH_ENABLE = no       # Bluetooth
CAPS_WORD_ENABLE = yes      # Caps Word feature
COMBO_ENABLE = yes          # Combo Keys feature
COMMAND_ENABLE = no         # Commands for debug and configuration
CONSOLE_ENABLE = no         # Console for debug
EXTRAKEY_ENABLE = yes       # Audio control and System control
KEY_OVERRIDE_ENABLE = yes   # Key Overrides feature
LTO_ENABLE = yes            # LTO to reduce compiled size
MOUSEKEY_ENABLE = no        # Mouse Keys
NKRO_ENABLE = yes           # N-Key Rollover
NO_USB_STARTUP_CHECK = no   # Disable initialization only when usb is plugged in
QMK_SETTINGS = yes          # VIAL QMK Settings tab
RGB_MATRIX_ENABLE = no      # Use RGB matrix
VIA_ENABLE = yes            # VIA support
VIAL_ENABLE = yes           # VIAL support
